---
- name: Generate VPN server secret key
  command: sqvpn genkey server.vpn-secret
  args:
    chdir: /var/opt/sqvpn
    creates: /var/opt/sqvpn/server.vpn-secret

- name: Extract VPN server public key
  command: sqvpn pubkey server.vpn-secret server.vpn-public
  args:
    chdir: /var/opt/sqvpn
    creates: /var/opt/sqvpn/server.vpn-public
