---
- name: Setup sqvpn-server service file
  template:
    src: sqvpn-server.service.j2
    dest: "/etc/systemd/system/sqvpn-server.service"

- name: Disable service sqvpn-server
  service:
    name: sqvpn-server
    enabled: no

- name: Stopped service sqvpn-server
  service:
    name: sqvpn-server
    state: stopped
  