---
- name: Copy sqvpn-start.sh script file
  template:
    src: sqvpn-start.sh.j2
    dest: "/usr/local/bin/sqvpn-start.sh"
    mode: 0755

- name: Copy sqvpn service file
  template:
    src: sqvpn.service.j2
    dest: "/etc/systemd/system/sqvpn.service"

- name: Enable service sqvpn
  service:
    name: sqvpn
    enabled: yes

- name: Restart service sqvpn
  service:
    name: sqvpn
    state: restarted
  